### ISSUE TITLE
Can't check Web Enrollment on CA

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#154]
Hello, as shown in the screenshot, the command fails not allowing to check if web enrollment is actually active:
![{9DE3CF59-9EEB-42EB-9E0F-77853C844A00}](https://github.com/user-attachments/assets/355cbe66-cac1-45d4-bf6c-0686b9f09e35)

**Comment by aniqfakhrul** [comment]
Fix pushed to main branch. Please verify if it works. Also extra tip, we have added a warning message in case the hostname couldnt be reached (dns issue or anything), you may want to use `-ns` or `--nameserver` flag for a custom nameserver because powerview.py uses system default resolver by default.

**Comment by GeisericII** [comment]
Can confirm it now works when `-ns` parameter is provided, thanks as always for the incredibly fast fix! It still throws a warning:

![Image](https://github.com/user-attachments/assets/9a161b6e-7bb5-47d8-9e7c-4d2d41e7cf15)

**Comment by aniqfakhrul** [comment]
We have fixed the dns caching issue that cause the warning message. Closing this as fixed. Thanks for the issue!
